name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAIs ChatGPT and subsequently creates a pull request with the generated code for review.'
author: 'hrUrian'

inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  REPOSITORY:
    description: 'The repository where the action will be executed.'
    required: true
  ISSUE_NUMBER:
    description: 'The number of the issue that triggered the action.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  SCRIPT_PATH:
    description: 'The path to the script that interacts with ChatGPT and generates code.'
    required: true
  LABEL:
    description: 'The label assigned to GitHub issues that should be processed by the AutoCoder action. Only issues with this label will trigger the code generation process.'
    required: true
    default: 'autocoder-bot'

outputs:
  pull_request_url:
    description: 'The URL of the pull request that has been automatically created, containing the auto-generated code for review and potential merging.'

runs:
  using: 'composite'
  steps:
    - name: Greet Users
      run: echo "Hello, welcome to AutoCoder! Let's generate some code."
      shell: bash
    - name: Generate Code from Issue
      run: |
        chmod +x ./scripts/script.sh
        ./scripts/script.sh ${{ env.GITHUB_TOKEN }} 'hrUrian/AutoCoder' ${{ inputs.issue_number }} ${{ env.OPENAI_API_KEY }}
        # The script that interacts with ChatGPT and generates code goes here.
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        base: main
        branch: "autocoder-branch-${{ github.event.issue.number }}"
        committer: autocoder-bot <actions@github.com>
        author: autocoder-bot <actions@github.com>
        title: "autocoder-branch-#${{ github.event.issue.number }}"
        labels: |
          autocoder-bot
#      run: |
#         The script that creates a pull request with the generated code goes here.
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    # Add additional steps as necessary, replicating the logic from your original workflow.