name: Generate code
on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  generate_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: AutoCoder Composite Action
        uses: hrUrian/AutoCoder@v0.2.0-alpha.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          LABEL: 'autocoder'

#jobs:
#  access_issue_info:
#    permissions:
#      contents: write
#      pull-requests: write
#    runs-on: ubuntu-latest
#    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v4
#      - name: Set permissions for script.sh
#        run: |
#          chmod +x ./scripts/script.sh
#      - name: Run script.sh
#        run: |
#          ./scripts/script.sh ${{ secrets.GITHUB_TOKEN }} 'hrUrian/AutoCoder' ${{ github.event.issue.number }} ${{ secrets.OPENAI_API_KEY }}
#      - name: upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: autocoder-artifact
#          path: autocoder-bot
#      - name: Download the autocoder artifact
#        uses: actions/download-artifact@v4
#        id: download-artifact
#        with:
#          name: autocoder-artifact
#          path: autocoder-artifact
#      - name: add changes
#        run: |
#          cp -R ${{ steps.download-artifact.outputs.download-path }}/* .
#          rm -r ${{ steps.download-artifact.outputs.download-path }}
#          rm -r autocoder-bot
#          git add .
#      - name: Create PR
#        uses: peter-evans/create-pull-request@v7
#        with:
#          base: main
#          branch: "autocoder-branch-${{ github.event.issue.number }}"
#          committer: autocoder-bot <actions@github.com>
#          author: autocoder-bot <actions@github.com>
#          title: "autocoder-branch-#${{ github.event.issue.number }}"
#          labels: |
#            autocoder-bot
