name: Generate code
on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set permissions for script.sh
        run: |
          chmod +x ./scripts/script.sh
      - name: Run script.sh
        run: |
          ./scripts/script.sh ${{ secrets.GITHUB_TOKEN }} 'hrUrian/AutoCoder' ${{ github.event.issue.number }} ${{ secrets.OPENAI_API_KEY }}
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot
      - name: Download the autocoder artifact
        uses: actions/download-artifact@v4
        id: download-artifact
        with:
          name: autocoder-artifact
          path: autocoder-artifact
      - name: checkout branch
        run: | 
          git checkout -b "autocoder-branch-${{ github.event.issue.number }}"
          git status
      - name: git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "autocoder-bot"
      - name: commit changes
        run: |
          cp -R ${{ steps.download-artifact.outputs.download-path }}/* .
          rm -r ${{ steps.download-artifact.outputs.download-path }}
          rm -r autocoder-bot
          git status
          git add * 
          git commit --allow-empty-message
          git status
          git diff main
      # - name: list artifact
        # run: | 
          # cp -R ${{ steps.download-artifact.outputs.download-path }} ..
          # rm -r ${{ steps.download-artifact.outputs.download-path }}
          # git commit -a --allow-empty-message 
          # git diff main
          # ls -R ${{ steps.download-artifact.outputs.download-path }}/../autocoder-artifact/
